services:
  postgres:
    container_name: "RinBot-DB"
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
    ports:
      - 5432:5432
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DATABASE}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
  
  pgadmin:
    container_name: "RinBot-PGAdmin"
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - 5050:80
  
  lavalink:
    container_name: "RinBot-Lavalink"
    image: fredboat/lavalink:latest
    environment:
      SERVER_PORT: ${LAVALINK_PORT}
      SERVER_PASSWORD: ${LAVALINK_PASSWORD}
      LAVALINK_YOUTUBE_PO_TOKEN: ${LAVALINK_YOUTUBE_PO_TOKEN}
      LAVALINK_YOUTUBE_VISITOR_DATA: ${LAVALINK_YOUTUBE_VISITOR_DATA}
    volumes:
      - ./rinbot/lavalink/plugins:/opt/lavalink/plugins
      - ./rinbot/lavalink/config/lavalink.yml:/opt/lavalink/application.yml
      - instance_data:/var/lib/rinbot
    expose:
      - ${LAVALINK_PORT}
    restart: unless-stopped

  django:
    container_name: "RinBot-Django"
    build:
      context: .
      dockerfile: Dockerfile.django
    environment:
      DJANGO_SETTINGS_MODULE: settings
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DJANGO_DEBUG: ${DJANGO_DEBUG}
      DJANGO_TIME_ZONE: ${DJANGO_TIME_ZONE}
      DJANGO_LANGUAGE_CODE: ${DJANGO_LANGUAGE_CODE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      BOT_DISCORD_TOKEN: ${BOT_DISCORD_TOKEN}
      BOT_RUN_WITH_DJANGO: ${BOT_RUN_WITH_DJANGO}
    volumes:
      - ./rinbot:/app
      - instance_data:/var/lib/rinbot
    ports:
      - 8002:8000
    depends_on:
      postgres:
        condition: service_healthy
      lavalink:
        condition: service_started
    restart: unless-stopped

volumes:
  instance_data:
    name: rinbot-instance-data
  postgres_data:
    name: rinbot-db-data
