version: "7.0.0 - Serenity"
debug: true
forward_discord_logs: false

status:
  language: en-GB
  interval: 5
  log: false

spam-filter:
  enabled: true
  time_window: 5
  max_per_window: 2

nsfw-extensions:
  danbooru:
    enabled: false
    api_key: null
  rule34:
    enabled: false
    api_key: null
  e621:
    enabled: false
    api_key: null

lavalink:
  host: RinBot-Lavalink
  port: 2001
  password: rinbot

testing-servers:
  - 1135238728403656834

tasks:
  - status_loop
  - birthday_check

internal-extensions:
  - event_handler

intents:
  dm_messages: true
  dm_typing: true
  guild_messages: true
  guild_typing: true
  guilds: true
  integrations: true
  voice_states: true
  webhooks: true
  members: true
  message_content: true
  moderation: true
  presences: true
  messages: true
  typing: true
  bans: true
