# Generated by Django 5.2 on 2025-04-21 13:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guildconfig',
            name='spam_filter_reason',
        ),
        migrations.AlterField(
            model_name='guildconfig',
            name='spam_filter_action',
            field=models.IntegerField(choices=[(0, 'Disabled'), (1, 'Delete'), (2, 'Kick')], validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)]),
        ),
    ]
