# Generated by Django 5.2 on 2025-04-21 14:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_remove_guildconfig_spam_filter_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='welcomechannels',
            name='colour',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(16777215)]),
        ),
    ]
