# Generated by Django 5.2 on 2025-04-21 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_alter_welcomechannels_colour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='welcomechannels',
            name='colour',
            field=models.CharField(max_length=7),
        ),
    ]
