# RinBot Configuration File

# Django Settings
django:
  secret_key: 'django-insecure-xfhm^=4y$ehn2^-i-*@ts-g+b*=5+^k9+gtk2#j1oz8dudu13j'
  debug: true
  allowed_hosts: []
  superuser:
    username: admin
    email: admin@example.com
    password: adminpassword

# Database Settings
database:
  name: rinbot
  user: rinbot
  password: rinbotpassword
  host: rinbot-postgres
  port: 5432

# Lavalink Settings
lavalink:
  password: youshallnotpass
  port: 2333

# Instance Directory Settings
instance:
  base_dir: /var/lib/rinbot
  subdirs:
    - logs/tracebacks
    - logs/lavalink
    - cache
